# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Uzer',
        ),
    ]
