# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_auto_20181011_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
