# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0007_auto_20181008_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_bio',
            field=models.TextField(max_length=50),
        ),
    ]
